let history=[],activeId=null,streaming=null;
const $=s=>document.querySelector(s);
async function load(){const r=await chrome.runtime.sendMessage({type:'QSA_GET_HISTORY'});history=r?.history||[];renderHistory();loadProfiles();}
function renderHistory(){const h=$('#history');h.innerHTML='';history.forEach(x=>{const b=document.createElement('div');b.className='history-item'+(x.id===activeId?' active':'');b.innerHTML=`<b>${escape((x.answer||'Nuova risposta').split('\n')[0].slice(0,45))}</b><small>${new Date(x.timestamp).toLocaleString()}</small>`;b.onclick=()=>showHistory(x);h.appendChild(b)});}
function showHistory(x){activeId=x.id;$('#welcome').style.display='none';$('#messages').innerHTML=`<div class="msg"><div class="role">${escape(x.provider||'AI')} · ${escape(x.model||'')}</div><div class="bubble">${escape(x.answer||'')}</div></div>`;renderHistory();}
function escape(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
async function loadProfiles(){const d=await chrome.storage.local.get(['profiles','activeProfileId','provider']);const sel=$('#profile');sel.innerHTML='';(Array.isArray(d.profiles)?d.profiles:Object.entries(d.profiles||{}).map(([id,p])=>({id,...p}))).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name||'Profilo';o.selected=p.id===d.activeProfileId;sel.appendChild(o)});$('#providerBadge').textContent=d.provider==='auto'?'Auto':(d.provider||'Gemini');}
$('#profile').onchange=async e=>{await chrome.storage.local.set({activeProfileId:e.target.value});await loadProfiles()};
$('#newChat').onclick=()=>{$('#welcome').style.display='block';$('#messages').innerHTML='';activeId=null;renderHistory()};
$('#settings').onclick=()=>chrome.runtime.sendMessage({type:'QSA_OPEN_SIDE_PANEL'}).catch(()=>{});
$('#theme').onclick=async()=>{const d=await chrome.storage.local.get('proTheme');const v=d.proTheme==='dark'?'light':d.proTheme==='light'?'auto':'dark';await chrome.storage.local.set({proTheme:v});applyTheme(v)};
function applyTheme(v){document.documentElement.style.colorScheme=v==='auto'?'light dark':v}
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{$('#input').value=b.dataset.prompt;$('#input').focus()});
$('#input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}});$('#send').onclick=sendText;
async function sendText(){const text=$('#input').value.trim();if(!text||streaming)return;$('#input').value='';$('#welcome').style.display='none';append('Tu',text,true);const ai=append('StudySnap AI','');streaming=ai.querySelector('.bubble');try{const p=chrome.runtime.connect({name:'qsa-chat'});let full='';p.onMessage.addListener(m=>{if(m.type==='chunk'){full+=m.text;streaming.textContent=full;streaming.scrollIntoView({block:'end'})}if(m.type==='done'){streaming.textContent=m.answer||full;streaming=null;p.disconnect() }if(m.type==='error'){streaming.textContent='Errore: '+m.error;streaming=null;p.disconnect()}});p.onDisconnect.addListener(()=>streaming=null);p.postMessage({type:'QSA_CHAT',text});}catch(e){streaming.textContent=e.message;streaming=null}}
function append(role,text,user=false){const m=document.createElement('div');m.className='msg';m.innerHTML=`<div class="role">${role}</div><div class="bubble ${user?'user':''}"></div>`;m.querySelector('.bubble').textContent=text;$('#messages').appendChild(m);m.scrollIntoView();return m}
chrome.runtime.onMessage.addListener(m=>{if(m.type==='QSA_HISTORY_UPDATED'){history.unshift(m.item);history=history.slice(0,80);renderHistory()}});load();

$('#exportMd').onclick=()=>{const text=history.map(x=>`## ${new Date(x.timestamp).toLocaleString()} — ${x.provider||'AI'}\n\n${x.answer||''}`).join('\n\n---\n\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`# StudySnap AI Pro — Cronologia\n\n${text}`],{type:'text/markdown'}));a.download='studysnap-history.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#exportPdf').onclick=()=>{const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>StudySnap AI Pro</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;line-height:1.55}h1{font-size:24px}.item{page-break-inside:avoid;margin-bottom:28px}.meta{color:#666;font-size:12px}pre{white-space:pre-wrap;font:inherit}</style></head><body><h1>StudySnap AI Pro — Cronologia</h1>${history.map(x=>`<div class="item"><div class="meta">${new Date(x.timestamp).toLocaleString()} · ${escape(x.provider||'AI')}</div><pre>${escape(x.answer||'')}</pre></div>`).join('')}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)};
